from django.db import models


GENRE_NAME_MAX_LENGTH = 200
BOOK_TITTLE_MAX_LENGTH = 200
BOOK_SUMMARY_MAX_LENGTH = 1000
BOOK_ISBN_MAX_LENGTH = 13
BOOKINSTANCE_IMPRINT_MAX_LENGTH = 200
BOOKINSTANCE_STATUS_MAX_LENGTH = 1
AUTHOR_FIRSTNAME_MAX_LENGTH = 100
AUTHOR_LASTNAME_MAX_LENGTH = 100
DISPLAYED_GENRE_MAX = 3
BOOKS_PER_PAGE_MAX = 10
INITIAL_DEADTH_DATE_OF_AUTHOR = '11/06/2020'
AUTHORS_PER_PAGE_MAX = 10


class LoanStatus(models.TextChoices):
    MAINTENANCE = 'm', 'Maintenance'
    ON_LOAN = 'o', 'On loan'
    AVAILABLE = 'a', 'Available'
    RESERVED = 'r', 'Reserved'
